allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@nerima-games/mc-meshing@0.1.5 || 0.1.6'
  - '@nerima-games/mc-noise@0.3.0 || 0.3.1'
  - '@nerima-games/mc-save@0.3.0 || 0.4.1'
  - '@nerima-games/mc-worldgen@0.2.0 || 0.3.1 || 0.3.2'
  - '@nerima-games/mc-physics@0.2.0 || 0.2.1 || 0.2.2'
  - '@nerima-games/mc-sim@0.2.0 || 0.2.1 || 0.4.1 || 0.4.2'
  - '@nerima-games/mc-kernel@0.7.0'
